### ISSUE TITLE
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'hackrf_sweep'

### ISSUE THREAD

**Issue by hecoupy** [ghostop14/sparrow-wifi#17]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ya/sparrow-wifi-master/sparrowhackrf.py", line 63, in run
    hackrfsweepProc = subprocess.Popen(params,stdout=subprocess.PIPE,stderr=subprocess.DEVNULL) # , shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'hackrf_sweep'

**Comment by ghostop14** [comment]
Hi hecoupy, if you have a hackrf, “apt install hackrf”.  Hackrf_sweep is part of the package.  If not the repo version may be old, in which case clone the hackrf repo from github and build it.  That should do the trick.
