### ISSUE TITLE
Error when attempting to Scan, and HackRF is greyed out under spectrum

### ISSUE THREAD

**Issue by mwk088** [ghostop14/sparrow-wifi#22]
Hello,

I have successfully installed sparrow-wifi and most of the dependencies into my Ubuntu 18.04 base docker image.  I can bring up the GUI, however, when tasking I get the error below.  Do you know what I am doing wrong or n additional package I may need?
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "sparrow-wifi.py", line 499, in run
    retCode, errString, wirelessNetworks = WirelessEngine.scanForNetworks(self.interface)
  File "/opt/truearrow/6.3/sparrow-wifi/wirelessengine.py", line 596, in scanForNetworks
    result = subprocess.run(['iw', 'dev', interfaceName, 'scan'], stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'iw': 'iw'`

In addition to the error, I also see the "HackRF sweep options" greyed out under the "Spectrum"

Thank you.

**Comment by nullx5** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'iw'

`sudo apt install iw` worked for me.
