### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hackrf_sweep'

### ISSUE THREAD

**Issue by curtisklarsen** [ghostop14/sparrow-wifi#38]
When I run "sudo ./sparrow-wifi.py" with the HackRF connected I get the following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "./sparrowhackrf.py", line 63, in run
    hackrfsweepProc = subprocess.Popen(params,stdout=subprocess.PIPE,stderr=subprocess.DEVNULL) # , shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hackrf_sweep'
Spectrum Length: 0
Test complete.

**Comment by curtisklarsen** [comment]
Nevermind.  I fixed this on ubuntu 20.04 by running "sudo apt install hackrf"
