### ISSUE TITLE
Could not install - so complicated

### ISSUE THREAD

**Issue by ThiloteE** [ghostop14/sparrow-wifi#72]
```
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ pip install gps3
Defaulting to user installation because normal site-packages is not writeable
Collecting gps3
  Downloading gps3-0.33.3-py2.py3-none-any.whl (29 kB)
Installing collected packages: gps3
Successfully installed gps3-0.33.3
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ sudo apt-get install python3-pip gpsd gpsd-clients python3-tk python3-setuptools python3-pyqt5.qtchart
[sudo] Passwort für thilo:                
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
python3-setuptools ist schon die neueste Version (45.2.0-1).
python3-pyqt5.qtchart ist schon die neueste Version (5.11.3+dfsg-2build1).
gpsd ist schon die neueste Version (3.20-8ubuntu0.4).
python3-tk ist schon die neueste Version (3.8.10-0ubuntu1~20.04).
gpsd-clients ist schon die neueste Version (3.20-8ubuntu0.4).
python3-pip ist schon die neueste Version (20.0.2-5ubuntu1.6).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ sudo pip3 install QScintilla gps3 dronekit manuf python-dateutil numpy matplotlib
Collecting QScintilla
  Using cached QScintilla-2.13.3-cp37-abi3-manylinux1_x86_64.whl (2.8 MB)
Collecting gps3
  Using cached gps3-0.33.3-py2.py3-none-any.whl (29 kB)
Collecting dronekit
  Using cached dronekit-2.9.2-py3-none-any.whl (56 kB)
Requirement already satisfied: manuf in /usr/local/lib/python3.8/dist-packages (1.1.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (2.8.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (1.22.3)
Collecting matplotlib
  Using cached matplotlib-3.5.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib/python3.8/dist-packages (from QScintilla) (12.11.0)
Collecting PyQt5>=5.15.4
  Using cached PyQt5-5.15.7-cp37-abi3-manylinux1_x86_64.whl (8.4 MB)
Requirement already satisfied: monotonic>=1.3 in /usr/local/lib/python3.8/dist-packages (from dronekit) (1.6)
Collecting pymavlink>=2.2.20
  Using cached pymavlink-2.4.34-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil) (1.14.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (7.0.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib) (4.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib) (20.3)
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from pymavlink>=2.2.20->dronekit) (0.18.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from pymavlink>=2.2.20->dronekit) (4.9.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in /usr/local/lib/python3.8/dist-packages (from PyQt5>=5.15.4->QScintilla) (5.15.2)
Installing collected packages: PyQt5, pymavlink, QScintilla, matplotlib, dronekit, gps3
  Attempting uninstall: PyQt5
    Found existing installation: PyQt5 5.14.1
ERROR: Cannot uninstall PyQt5 5.14.1, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps PyQt5==5.14.1'.
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ pip install --force-reinstall --no-deps PyQt5==5.14.1
Defaulting to user installation because normal site-packages is not writeable
Collecting PyQt5==5.14.1
  Downloading PyQt5-5.14.1-5.14.1-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (63.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 MB 3.1 MB/s eta 0:00:00
Installing collected packages: PyQt5
  WARNING: The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/home/thilo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyQt5-5.14.1
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ sudo pip install --force-reinstall --no-deps PyQt5==5.14.1
Collecting PyQt5==5.14.1
  Downloading PyQt5-5.14.1-5.14.1-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (63.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 MB 3.1 MB/s eta 0:00:00
Installing collected packages: PyQt5
  Attempting uninstall: PyQt5
    Found existing installation: PyQt5 5.14.1
ERROR: Cannot uninstall PyQt5 5.14.1, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps PyQt5==5.14.1'.
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ sudo ./sparrow-wifi.py
sudo: ./sparrow-wifi.py: Befehl nicht gefunden
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi $ sudo ./sparrow-wifi.py
```

**Comment by ThiloteE** [comment]
```
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi/sparrow-wifi-master $ sudo ./sparrow-wifi.py
[sudo] Passwort für thilo:                
Traceback (most recent call last):
  File "./sparrow-wifi.py", line 45, in <module>
    from wirelessengine import WirelessEngine, WirelessNetwork
  File "/home/thilo/Programme/Sparrow-wifi/sparrow-wifi-master/wirelessengine.py", line 29, in <module>
    from sparrowgps import SparrowGPS
  File "/home/thilo/Programme/Sparrow-wifi/sparrow-wifi-master/sparrowgps.py", line 27, in <module>
    from gps3.agps3threaded import AGPS3mechanism
ModuleNotFoundError: No module named 'gps3'
thilo@thilo-Aspire-ES1-311 ~/Programme/Sparrow-wifi/sparrow-wifi-master $ 

```
