### ISSUE TITLE
TypeError: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by asynctdm** [ghostop14/sparrow-wifi#84]
I am not able to access telemetry window at all , have installed all the dependencies in the documentation . Any help appreciated 
```
Traceback (most recent call last):
  File "/usr/share/sparrow-wifi/sparrow-wifi.py", line 1885, in onShowTelemetry
    telemetryWindow = TelemetryDialog()
  File "/usr/share/sparrow-wifi/telemetry.py", line 158, in __init__
    self.setGeometry(self.geometry().x(), self.geometry().y(), desktopSize.width() /2,desktopSize.height() /2)
TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 3 has unexpected type 'float'
zsh: abort      sudo sparrow-wifi
```

**Comment by ghostop14** [comment]
Hi asynctdm.  Try a fresh pull from git.  This issue came up late last year and I pushed updates.
